### ISSUE TITLE
Pet Changes on Death

### ISSUE THREAD

**Issue by BasvdW22** [DSH105/EchoPet#306]
If someone choose a pet like a black baby ocelot with a specefic name and he die, sometimes the pet change into a normal ocelot without a name but it is still a pet, and sometimes your normal pet is still there but there's also a normal ocelot, also a pet, without a name! I can remove the pet with /killall, but I can't kill it the normal way.
Sorry for my bad English, I'm Dutch!

**Comment by brw** [comment]
Dang, found this again browsing through my GitHub history. This was such a long time ago, my English was horrible back then lol.
