### ISSUE TITLE
EchoPet Linked With Buycraft

### ISSUE THREAD

**Issue by Killerboss707** [DSH105/EchoPet#395]
Hi, i was wondering if it was possible to link Echo pet with buy craft so, you know people can donate to get pets. 
Thanks, Killerboss707

**Comment by Raven2099** [comment]
so where do i paste these commands to use Echopet with Buycraft?

(using PeX)  thanks in advance

**Comment by stuntguy3000** [comment]
@Raven2099 Look into how BuyCraft works, contact them if needed.
