### ISSUE TITLE
1.8 Client Crash on Spigot 1.7.10

### ISSUE THREAD

**Issue by 0zlw** [DSH105/EchoPet#426]
I am getting a clientside crash after renaming a human pet and looking at it.

ClientSide Crash Report: http://pastebin.com/AUe8q2vi

Client Version: 1.8
Spigot Version: This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
Echopet Version: v2.5.1-SNAPSHOT-b20

Happy to provide additional log evidence or otherwise.

Edit: Happened after creating a Human Pet, then renaming it 'IceCubesBurnings', then crash when looking at it (I believe)

Edit Edit: I idle on the irc channel with the username 'zlw'

**Comment by DSH105** [comment]
Closing this as human pets are deprecated and no longer supported.
