### ISSUE TITLE
EchoPet v2.5.0-b16 - git-MCPC-Plus-1.7.2-R0.4-forge1098-82 (MC: 1.7.2) - errors

### ISSUE THREAD

**Issue by minecraft7net** [DSH105/EchoPet#431]
EchoPet v2.5.0-b16 - git-MCPC-Plus-1.7.2-R0.4-forge1098-82 (MC: 1.7.2) - errors

http://pastebin.com/TR28kkPm

http://pastebin.com/ran3C7rn

**Comment by DSH105** [comment]
#391
