### ISSUE TITLE
Creeper power data permission doesn't work

### ISSUE THREAD

**Issue by MyzelYam** [DSH105/EchoPet#441]
I tried to give my players the following permissions, but they still weren't able to toggle the power effect of creepers. All other data types work. They do have permission to use the creeper pet and the creeper menu. No errors in console, just the default you don't have permission to do that message.

- echopet.pet.data.power
- echopet.pet.type.creeper.power
- echopet.pet.data.*

Version of spigot: Latest patch

Version of EchoPet: 2.5.0-b16

I really hope you could please fix that!

Thank you.

**Comment by DSH105** [comment]
The permission for that data type is actually `echopet.pet.type.creeper.powered`. I've updated the wiki to reflect this, as it previously stated that the permission was `power`. My apologies for the confusion.

Additionally, the wildcard node for creeper pet data wasn't defined by EchoPet. I've rectified this in https://github.com/DSH105/EchoPet/commit/9b9a6faca961ab15180fd1a65fa419acedf7b87a. This means that `echopet.pet.type.creeper.*` and `echopet.pet.data.*` should now function correctly.

Sorry for the (extremely) late reply and resolution!
