### ISSUE TITLE
1.6 suggests update 1.5

### ISSUE THREAD

**Issue by dwilson390** [DSH105/EchoPet#457]
Hey!

Just updated echopet, loving it! :D one thing I have found is on logging in and in console I am told there is a newer version availble (1.5) when I'm on 1.6. Thanks!

**Comment by DSH105** [comment]
I've received mixed reports about this for a while now, but I'm not sure as to why it occurs.

I'll close this issue as it's only a minor problem. EchoPet uses an updater which is DBO-specific anyway (a platform that is quickly becoming obsolete).
