### ISSUE TITLE
Pet name colors resetting on teleport.

### ISSUE THREAD

**Issue by zDylann** [DSH105/EchoPet#458]
Teleporting with a pet will reset the pets name color. Newest version of EchoPet on spigot 1.8. It seems like any kind of teleport, at first I thought it was just world changing.

**Comment by Spirit55555** [comment]
Looks like the problem is located here:
https://github.com/DSH105/EchoPet/blob/master/modules/EchoPet/src/main/java/com/dsh105/echopet/api/PetManager.java#L340

https://github.com/DSH105/EchoPet/blob/master/modules/EchoPet/src/main/java/com/dsh105/echopet/api/PetManager.java#L350

**Comment by DSH105** [comment]
Hopefully the above commit fixes the problem. Thanks for pinpointing it @Spirit55555 :).

**Comment by lasercar** [comment]
I still have this problem.
Using EchoPet 2.8.0-b52 and Spigot 1.8.8 (git-Spigot-fdc1440-53fac9f)
