### ISSUE TITLE
Entity registration

### ISSUE THREAD

**Issue by DSH105** [DSH105/EchoPet#462]
Entity registration still appears to be causing a few problems, the most prominent being that it seems to be impacting on the functionality of spawn eggs.

[This method here](https://github.com/Bukkit/mc-dev/blob/master/net/minecraft/server/EntityTypes.java#L96-L114) appears to be the one that EchoPet is interfering with. It's likely a problem with the modifications that are dynamically added/removed where necessary in [this method](https://github.com/DSH105/EchoPet/blob/master/modules/API/src/main/java/com/dsh105/echopet/compat/api/registration/PetRegistry.java#L110-L128). Consequently, the [map modifier](https://github.com/DSH105/EchoPet/blob/master/modules/API/src/main/java/com/dsh105/echopet/compat/api/registration/EntityMapModifier.java) probably isn't working as it should.

I haven't looked into it much beyond that, but I'm reporting it here in case anyone else has any other information.

**Comment by BlackBeltPanda** [comment]
This problem is still occurring for me on Echopet b32
