### ISSUE TITLE
Server crashes on summoning pet

### ISSUE THREAD

**Issue by ComicSeckz** [DSH105/EchoPet#467]
Hello,
I am very interested in using this plugin as a donator cosmetic perk but I have a problem. When I summon my pet it just causes the server to crash instantly. I have attached a pastie of the console after I type the command. Also, some pets don't seem to cause the crash whereas others do, are there any pets I should not let people use as it causes a crash. From what I can tell it happens when I summon a human pet, but I'm not 100% sure.
http://pastie.org/9804744
Thanks in advance,
Raul

**Comment by DSH105** [comment]
Closing - human pets are deprecated and no longer supported.
