### ISSUE TITLE
Pets won't spawn

### ISSUE THREAD

**Issue by Wkronfeld** [DSH105/EchoPet#477]
Just like the title says, pets won't spawn. All commands work but not pets get spawned. I am running the latest version of echopet, and spigot (1.8). if anyone could help me, that would be great. 

Thank you!

**Comment by DSH105** [comment]
If you can provide a stack trace, I'll look into why the pets aren't spawning for you :).

**Comment by Wkronfeld** [comment]
Figured it out. World guard doesn't work with it. Any idea when this will
be fixed?

**Comment by DSH105** [comment]
EchoPet has integrated WorldGuard support out of the box, but it shouldn't interfere unless configured to do so. Is WorldGuard blocking all pet spawning?

**Comment by Wkronfeld** [comment]
I am using the world guard 6 beta for 1.8.

**Comment by DSH105** [comment]
I'm still not clear on what is supposed to be fixed.

**Comment by Wkronfeld** [comment]
It's not your fault, it's on the world guard side. Go ahead and close this.
Sorry about eating some of your time up.

**Comment by DSH105** [comment]
That's completely fine :).

EchoPet is supposed to override WorldGuard when spawning pets though.
