### ISSUE TITLE
Cannot use mob spawn eggs (EP 2.6.0-b28

### ISSUE THREAD

**Issue by TNTUP** [DSH105/EchoPet#479]
Im unsure, but I think EchoPet blocks mob eggs usage because when a player buys a cow egg (for farm purposes) nothing is outputted... Nothing is done with the egg, doesn't spawn.

A player reported this issue, I tried it too and it couldn't spawn. I bet its EchoPet because yesterday it was fine. Seeing in the console it says "17:14:11 CONSOLE: WARN]: Skipping Entity with id 50" tried to spawn a creeper with the egg 383:50. Any idea why? Using the latest one from BukkitDev. I should try your dev builds :)

**Comment by REMLIK1** [comment]
I am also using EP version 2.6 and experience the same issue. No clue why it is affecting the spawn eggs.

**Comment by TNTUP** [comment]
Well, I grabbed the 2.6.1-b32 on DSH105's CI and it fixed the issue, though the one on BukkitDev this issue occurs.

**Comment by REMLIK1** [comment]
Nice I will install it! Did you remove the old one completely including the generated folder?

**Comment by TNTUP** [comment]
Nope, Only replaced the file and restarted server its fixed ;)

**Comment by DSH105** [comment]
Closing - see #462
