### ISSUE TITLE
New Feature - Player Points support

### ISSUE THREAD

**Issue by Vidsify** [DSH105/EchoPet#487]
Hi

Is it possible you could add support for PlayerPoints. On my network I have a points system and people get points by voting etc then can buy cosmetics in hubs/lobbies. I really would like the ability for them to buy pets with those points. I believe that PlayerPoints already has an Api which can be used. So if a pet cost 500 points and the player had 1000 they points will be subtracted, player gets pet forever, leaving them with 500 points.

Link to plugin: http://dev.bukkit.org/bukkit-plugins/playerpoints/

Thanks in advanced

**Comment by sanjay900** [comment]
Could you not just make a plugin to do this yourself?

**Comment by Vidsify** [comment]
I don't know how to make a pets plugin my knowledge of the Bukkit api isn't that advanced

**Comment by sanjay900** [comment]
No, use EchoPet's api.

**Comment by sanjay900** [comment]
That's the whole point of an API, you can extend EchoPet's functionality and add your own things.

**Comment by DSH105** [comment]
I've probably said this elsewhere; I have to limit feature inclusions into the main branch to prevent the plugin from becoming too bloated. EchoPet has a simple API which can be used to achieve this.
