### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by Vidsify** [DSH105/EchoPet#488]
Hi

In our lobby we have ChestCommands to make custom GUIs and menus. I am making a vanity shop for players when they donate/vote so they can get points and buy things.

When i go to click on the Vanity shop and click the pets side it opens fine. When I click the pets it just spawns in that type of animal. I can't do anything with it like ride it etc. However, the human pet seems to crash the server. We are using EchoPet. If you do /pet select that doesn't work either.

Here are all the crash reports:
http://pastebin.com/w9fjFfEQ
http://pastebin.com/553v7wz8
http://pastebin.com/PynRUg2u

**Comment by RossStill** [comment]
What's your server IP address?

**Comment by Vidsify** [comment]
Our IP at the minute is changing I'll give it to you once we have got it.

**Comment by Vidsify** [comment]
192.99.20.209:27243 its located in the redstone dust. Please tell me if you can access it not as I'm not sure what its set to

**Comment by DSH105** [comment]
Are you running the protocol 1.7/1.8 Spigot?

**Comment by Vidsify** [comment]
Not as I know of. We are running spigot 1.7.10 but come to think of it we might be as I joined with a 1.8 client.

**Comment by DSH105** [comment]
If so, `v2.6.0` (`b28`) is not compatible with that particular server version. You can either:
a) Downgrade EchoPet to the previous release.
b) Update your server to 1.8.

Hopefully that helps fix your problem :).

**Comment by Vidsify** [comment]
Problem Fixed thank you :D :+1:

**Comment by DSH105** [comment]
yay! :D
