### ISSUE TITLE
Players suffocating in walls while riding pets

### ISSUE THREAD

**Issue by comfortedbasher** [DSH105/EchoPet#491]
When a player runs into a wall or and object above 2 blocks high they start to suffocate inside the object they hit they can  backout of the wall but it is always happening

**Comment by DSH105** [comment]
I can't really do much to prevent this, sorry.

**Comment by CaptainBern** [comment]
Will close this as it's useless to keep this open. (Not really fixable on our side)

**Comment by comfortedbasher** [comment]
its a pretty pretty big fucking issue but whatever
