### ISSUE TITLE
Spawn Eggs won't work after Pet of that Type is summoned

### ISSUE THREAD

**Issue by cindyker** [DSH105/EchoPet#495]
You get this in the server log when trying to use the spawn egg.
[22:21:41 WARN]: Skipping Entity with id 92
[22:21:42 WARN]: Skipping Entity with id 92

The Cow egg worked just fine, until I summoned a pet cow. Then the eggs stopped working and those lines appear in the log when I try to use one.

**Comment by ErazePlaysMC** [comment]
I also have this issue. It means i cannot sell spawn eggs at all on my server whilst also using EchoPet. Any help would be appreciated! Cheers~

**Comment by cindyker** [comment]
ErazePlaysMC - https://ci.dsh105.com/job/EchoPet-v2/
Use the latest build from here.  That issue has been fixed in it.

**Comment by cindyker** [comment]
FIx with : Build#32 from https://ci.dsh105.com/job/EchoPet-v2/

**Comment by ErazePlaysMC** [comment]
I'm afraid it hasn't. The last build was almost three months ago. This issue was created 11 days ago, and i know more than 3 other people having the same problem.

**Comment by DSH105** [comment]
And it was fixed three months ago: #462. The only people experiencing problems are those running older builds.
