### ISSUE TITLE
Server crash 2.6.0

### ISSUE THREAD

**Issue by rangewonk** [DSH105/EchoPet#496]
I just updated echo pet to 2.6.0. It loaded fine then this error happened and the server shut down.
http://hastebin.com/obiwukimoq.avrasm

**Comment by DSH105** [comment]
I can only guess your running that Spigot protocol build, in which case the answer is; no, v2.6.0 lost compatibility for that specific server version. If you still wish to run that build, downgrade to the previous EchoPet release.

Hopefully that solves your problem.
