### ISSUE TITLE
Spigot 1.8.3 Support

### ISSUE THREAD

**Issue by mibby** [DSH105/EchoPet#498]
@DSH105 
Hey DSH. :) EchoPets needs to be updated to support Spigot / Bukkit 1.8.3.

```
[15:04:52] [Server thread/INFO]: [EchoPet] Enabling EchoPet v2.6.1-SNAPSHOT-b32
[15:04:52] [Server thread/INFO]: [EchoPet] [INFO] [0;31;1mEchoPet [0;33;22m2.6.1-SNAPSHOT-b32[0;31;1m is not compatible with this version of CraftBukkit[m
[15:04:52] [Server thread/INFO]: [EchoPet] [INFO] [0;31;1mInitialisation failed. Please update the plugin.[m
```

**Comment by DSH105** [comment]
At the moment, I don't have plans to update EchoPet 2 to Spigot 1.8.3. There are reasons why, but I'm not open to discussing it here. Sorry :(.

**Comment by mibby** [comment]
:(

**Comment by DSH105** [comment]
I'll be happy to continue on with the existing Sponge port later in the year, though.

**Comment by mibby** [comment]
I'll be happy to help test and debug whenever a functional sponge server build is ready. :) Just a shame it isn't a simple port to 1.8.3 to keep EchoPets functional in the meantime, as sponge has been delayed quite a bit since originally announced.

**Comment by DSH105** [comment]
I have neither an IDE nor the code available locally anyway.

**Comment by Kmancrazy** [comment]
Hello, I am kedric, and i was wondering if you could point us in the direction of the problem? Is it just renaming things? Or is it bigger then that, like nms code that has been changed. I really love your plugin and don't want it to die out! I completely respect your decision in not continuing it, but if you could tell us what is the problem that would be great :) thank you!

**Comment by DSH105** [comment]
It's not that there is a specific problem or that this particular update is difficult, but more that I (at the moment) am not currently able to dedicate enough time to sustaining both the code and sufficient community support. I'm all for keeping the existing Sponge/Bukkit(/Glowstone) branch active and eventually promoting it as the next major major release nearer to the end of the year, but at the moment I have other important priorities/commitments/etc. that require my attention (one of which is graduating secondary education). That and I am also 'taking a break' from the general Minecraft community (as the result of other contributing factors as well as what I have already mentioned).

In saying that though, my current stance on this project is that it is *not dying*, but rather that development is being *suspended or postponed* until later. I've also left development at a fairly 'stable' state in comparison to previous releases, considering the volatility of both the plugin's NMS interaction and relatively ancient backend (but I wouldn't really suggest anyone with any sanity left attempting to decipher it).

*If* I find the time to dig out my old laptop which still has my development tools installed, I may remap a new module to the 1.8.3 obfuscation changes.

**Comment by Kmancrazy** [comment]
Ok, thank you! We really do enjoy your plugin, we cant wait until it is updated :)

**Comment by South-Paw** [comment]
@DSH105 We'd love to see a 1.8.3 Spigot update if you can find the time - good luck with finishing your studies sir!

**Comment by mibby** [comment]
If there is anything I can do to help get EchoPets updated for 1.8.3, let me know. :)

**Comment by DSH105** [comment]
I pushed a 1.8.3 module over at the [`MC-183`](https://github.com/DSH105/EchoPet/tree/MC-183) branch (CI builds can be found [here](https://ci.dsh105.com/job/EchoPet-v2%20(1.8.3)/)).

I haven't really done much here since:
- it's not really a complex update,
- I can't really remember (all that well) what most of this messy NMS stuff in EchoPet does anyway, and
- all that other stuff.

It compiles; so that's a plus. I've no idea if it does much else other than crash servers with spectacular precision. If it works, yay.

**Comment by CaptainBern** [comment]
Will close this now since it's "solved"-ish

**Comment by DSH105** [comment]
:+1:

**Comment by mibby** [comment]
@DSH105 

Current issues I've experienced with build 2. https://ci.dsh105.com/job/EchoPet-v2%20(1.8.3)/2/

* Pets do not move when spawned in (besides enderdragon).
* Pets do not follow the owner, look at the owner, or teleport when a certain distance away.
* '/pet list' causes an error. http://paste.ubuntu.com/10592262/
* Pet bat is not flying. It is spawned on the ground. As well as riding it, you are not able to fly with it.
* Pet blaze, same as bat. Can't fly. (Seems all mobs that would otherwise be flying aren't. Including wither, squid, ghast, etc.)
* All pets, can't jump while riding.
* Pet enderdragon, controls are inverted. W = left, D = forward, S = right, A = forward, Can't change elevation, can't fly, can't use mouse movement, pet stays still while on it.
* Pet horse resets orientation (to where the horse is looking?) when right clicking on it.
* I personally keep human pet disabled, but enabling & testing, it says Human pet type is not compatible with this server version.

Other than that and any current open tickets I have, everything seems to work. I haven't tested to see if it crashes when other players are online and near, only tested by myself.

**Comment by DSH105** [comment]
Most of those are probably because the doTick method in nms.Entity is now final and cannot be overridden, meaning that the pet AI can't be 'ticked'.

**Comment by DSH105** [comment]
See PR #503 (above).
