### ISSUE TITLE
Command Prefixes

### ISSUE THREAD

**Issue by 1234filip** [DSH105/EchoPet#499]
Hey
I am working on professional server and your plugin is perfect except the command prefixes.([Echo-Pet] Your pet has been enabled.)
How do I disable them?
please respond asap

**Comment by CaptainBern** [comment]
Not possible unless you compile it yourself and change [this](https://github.com/DSH105/EchoPet/blob/master/modules/EchoPet/src/main/java/com/dsh105/echopet/EchoPetPlugin.java#L83) and compile your own version of EchoPet. 

But if the plugin is perfect for your server then why not give a little bit of credit? :) 
I will close this for now, if you have any more questions; feel free to post them here or hop by on IRC (#dsh105)
