### ISSUE TITLE
Change the EchoPet messages?

### ISSUE THREAD

**Issue by ShatteredDeath** [DSH105/EchoPet#501]
hi i really <3 this plugin! But is there a way to Change the Echo-Pet messages?

So for example if i type "/pet cow" it responds in: 
"&4[&cEchoPet&4] &eA &6Cow &enow follows close behind you."
is there a way to change these messages, if not all, any?

thanks for your time. Best Regards ~ ShatteredDeath

**Comment by DSH105** [comment]
Yep, the options are listed in the language/messages file. I can't remember the *exact* name off the top of my head, but it's in the EchoPet data folder as something like 'lang.yml'

**Comment by ShatteredDeath** [comment]
OMG THANK YOU! :D

**Comment by DSH105** [comment]
;D
