### ISSUE TITLE
Shop enable/disable?

### ISSUE THREAD

**Issue by ShatteredDeath** [DSH105/EchoPet#504]
I was also wondering if there's a way to set up a shop like Hypixal or some other servers, were you're able to buy a pet, then buy another one and can enable/disable them, not having to re-buy them, so for example: I have bought a Blaze pet, and it gets enabled. Then i buy an Enderman pet, and that gets enabled...but if I want to re-enable the blaze it says I have to re-buy it.

Please haalp :3 ~ ShatteredDeath

**Comment by DSH105** [comment]
If you can sell access to commands or permissions, that should function similar to what you're after. There isn't any support for economy plugins in EchoPet though :(.

**Comment by ShatteredDeath** [comment]
i can set it up in chest commands :D thank you!

**Comment by ShatteredDeath** [comment]
w8...I don't think I explained that right...

**Comment by ShatteredDeath** [comment]
I mean, I want them to buy pets, then they can buy multiple more, and then enable them instead of having to re-buy them :/

**Comment by DSH105** [comment]
So once bought, you have 'lifetime' access to a certain pet type? I don't know my way around plugins that have this functionality, but they *should* allow you to do so by selling permissions.

If I understand correctly, this is how you would want to set it up:

e.g.
- Player buys pet (e.g. `/buy pet cow`).
- Economy plugin enables access to that pet type by giving them the required permission: `echopet.pet.type.<pet_type>`, etc.
- Player can now use `/pet cow`.
- Player buys another pet (`/buy pet creeper`).
- Plugin assigns permission access and player can use both `/pet cow` and `/pet creeper`.

Or, if you don't want them to have access to both pets, when a player buys a new pet type, have the plugin remove permission for the existing type.

e.g.
- Player has access to `/pet cow`.
- Player buys a creeper pet.
- Economy plugin assigns access to `/pet creeper` and removes access to `/pet cow`.

**Comment by ShatteredDeath** [comment]
thanks!
