### ISSUE TITLE
Just wondering: Potential memory leak?

### ISSUE THREAD

**Issue by ItsHarry** [DSH105/EchoPet#508]
I don't know if this is actually an issue, but what exactly is the idea behind this?

https://github.com/DSH105/EchoPet/blob/master/modules/EchoPet/src/main/java/com/dsh105/echopet/listeners/ChunkListener.java

Won't the chunk stay loaded forever if you cancel the event?

**Comment by DSH105** [comment]
I'm honestly not sure what that listener was supposed to achieve either.

**Comment by ItsHarry** [comment]
Haha =_

**Comment by DSH105** [comment]
Hopefully that should resolve any of those potential memory leaks on chunk unload.

**Comment by ItsHarry** [comment]
Thanks
