### ISSUE TITLE
1.8.3 Spigot Build - Error.

### ISSUE THREAD

**Issue by GamermadHD** [DSH105/EchoPet#509]
Hey just updated my server to the latest spigot build and this happens - 
[22:49:01] [Server thread/INFO]: [EchoPet] Enabling EchoPet v2.6.1-SNAPSHOT-b37
[22:49:01] [Server thread/INFO]: [EchoPet] [INFO] [EchoPet [2.6.1-SNAPSHOT-b37[is not compatible with this version of CraftBukkit]
[22:49:01] [Server thread/INFO]: [EchoPet] [INFO] [Initialisation failed. Please update the plugin.]

**Comment by CaptainBern** [comment]
https://github.com/DSH105/EchoPet/pull/503

**Comment by GamermadHD** [comment]
So is there a working build?

**Comment by CaptainBern** [comment]
@GamermadHD: No, that's why it's currently being worked on. :stuck_out_tongue_winking_eye:

**Comment by DSH105** [comment]
The existing 1.8.3 builds are *mostly* bug free, but it's your responsibility if you choose to run them before an official release is published :).

**Comment by GamermadHD** [comment]
Okay Thanks

On 3 April 2015 at 23:04, Jason <notifications@github.com> wrote:

> The existing 1.8.3 builds are *mostly* bug free, but it's your
> responsibility if you choose to run them before an official release is
> published :).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DSH105/EchoPet/issues/509#issuecomment-89434315>.
>



-- 
Kieran Tronier
