### ISSUE TITLE
Lag issues

### ISSUE THREAD

**Issue by ItsHarry** [DSH105/EchoPet#513]
Hey there,

I'm experiencing a lot of lag in one of my servers. For some reason, Spigot Timings tells me it is caused by EchoPet, although I can't actually see it in the timings.

Here is a screenshot of the timings:
![img](https://cloud.githubusercontent.com/assets/914835/7005448/5a8374fe-dc78-11e4-8663-0e5357b1c767.png)

Any idea what might be causing this?

**Comment by i9hdkill** [comment]
Also some lag issues with Echo Pet 1.8.3 Build 15
http://timings.aikar.co/?url=10774597
But not sure if that's Echo Pet or another Plugin that does chunk loading/unloading or something like that.
![unbenannt](https://cloud.githubusercontent.com/assets/4679374/7050317/ddb77a6a-de20-11e4-9fff-9a0b423e5d13.png)

**Comment by ItsHarry** [comment]
^ ChunkUnloadEvent was already removed in #508

**Comment by i9hdkill** [comment]
Ah I see. This patch seems to be mising in the 1.8.3 version

**Comment by DSH105** [comment]
Yeah, that's because the patch was added while the MC-183 branch was still being worked on. I decided it would be easier to leave the merging until the very end.

**Comment by i9hdkill** [comment]
Any chance that you add your chunk patch to the 1.8.3 branch anyway? Because it's a major lag issue.
I would really appreciate it.

**Comment by DSH105** [comment]
The branch is mostly finished now anyway. The only thing missing is proper 'walking' and menu integration for the newer pet types. Is it alright if it's not merged for a few more days?

If the branch isn't finished/merged by Saturday, I'll copy the patch over to `MC-138`.

**Comment by i9hdkill** [comment]
No worries, that will work out:) Thanks, keep up the good work!

**Comment by ItsHarry** [comment]
It happened again :(

![277c467d95054885ab85ddbdcebdaed8](https://cloud.githubusercontent.com/assets/914835/8603769/98999902-267a-11e5-99c0-653a6139ac8b.png)

**Comment by i9hdkill** [comment]
You are using an old version...

**Comment by ItsHarry** [comment]
That version doesn't seem to work on PaperSpigot, and it also doesn't include #539

**Comment by ItsHarry** [comment]
Nevermind it, I'll figure something out. I'll make a new ticket if the issue still happens on the latest version.
