### ISSUE TITLE
"/pet list" is broken

### ISSUE THREAD

**Issue by mickare** [DSH105/EchoPet#515]
Spigot Version: CraftBukkit version git-Spigot-4c7d0c0-7d020a7 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

EchoPet Version: 2.6.1-SNAPSHOT-b15

Error Log: http://pastebin.com/igUs0a9d

**Comment by JOPHESTUS** [comment]
@lol768 :clap:

**Comment by lol768** [comment]
.. what

**Comment by DSH105** [comment]
Why create a new issue when it is perfectly clear on the existing 1.8.3 PR that this is an issue that is being worked on? If you are using those builds you should at least be aware of the conversation surrounding them.

**Comment by mickare** [comment]
My mistake. Normaly those are listed as issues, and resolved in commits. But commits and open issues didn't list it. It's a philosophical question.
Keep up the good work. ^^

**Comment by DSH105** [comment]
Ah, in that case your search may have been restricted to issues only (e.g. [this list](https://github.com/DSH105/EchoPet/issues?utf8=✓&q=is%3Aopen) includes both issues and pull requests).

My apologies for being a little fiery.
