### ISSUE TITLE
I have a problem with EchoPets...

### ISSUE THREAD

**Issue by RoyOMGH** [DSH105/EchoPet#518]
Hello I have just recently installed EchoPets. i was typing in the commands to get a pet, then it said that EchoPets 2.6.0 was not compatible, and I needed to update. I need help!

**Comment by DSH105** [comment]
See #503

**Comment by RoyOMGH** [comment]
![issue](https://cloud.githubusercontent.com/assets/12144925/7367169/4a25930e-ed52-11e4-9af1-e40a23e3a3f8.PNG) This is what it says, I checked the link you provided, but I am still confused.. Do I need Spigot instead of CraftBukkit?

**Comment by DSH105** [comment]
I'm assuming you're running 1.8.3, a server version which no public release of EchoPet is compatible with (yet). If you're interested in running mostly stable development builds which *are* compatible with 1.8.3, you can acquire them at the above link ([direct CI link here](https://ci.dsh105.com/job/EchoPet-v2%20(1.8.3)/)).

Spigot/CraftBukkit doesn't matter :).

**Comment by RoyOMGH** [comment]
Oh okay, but the weird thing is, that my CraftBukkit is 1.8.0 not 1.8.3 o:

**Comment by DSH105** [comment]
It shouldn't show that for 1.8 :o

**Comment by RoyOMGH** [comment]
Hello once again, I am so sorry for wasting your time, but I recently checked my server, it is 1.8.3 it's my fault, I am so sorry for wasting your time again! :) I feel really bad now, i could have sworn it was a 1.8.0 server. Sorry for wasting your time once again!

**Comment by DSH105** [comment]
No problem at all. I'm happy to help if you come across any issues again :).
