### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by Juusotnt** [DSH105/EchoPet#521]
Hello.
my name is juusotnt
i play in a server where is cops and robbers minigame
the server uses echopets.
but it is realy annoying that people abuse that pet / animal in pvp / fights.
can you do something so in combat you would fell of the pet and could not use it while being in combat?
this possibility could be added to the config file. it would help alot. thank you <3

**Comment by DSH105** [comment]
You can create a WorldGuard region in which pets are not allowed into using the [worlds/regions section of the config](https://github.com/DSH105/EchoPet/wiki/Config.yml#worlds-section).
