### ISSUE TITLE
Won't enable with Spigot 1.8.4

### ISSUE THREAD

**Issue by NotNorom** [DSH105/EchoPet#525]
After updating Spigot from 1.8.3 -> 1.8.4 the plugin won't load with the message shown on the picture: " EchoPet 2.7.1-SNAPSHOT-b42 is not compatible with this version of CraftBukkit  - Initialisation failed. Please update the plugin."

Because this is indeed the latest build marked as "working", I tried a few older versions (e.g. 2.6.0) which didn't seem to work either (same message as for 2.7.1-blah).
This probably isn't a bug of the plugin itself, still interesting.

![image](https://cloud.githubusercontent.com/assets/7762532/7684229/bd369748-fd84-11e4-9ee4-7651e4885f65.png)

Thanks~

**Comment by SmallSansSerif** [comment]
Yeah they bumped the NMS version. Can this be updated for 1.8.4 please.

**Comment by Htgan** [comment]
Not even 1.8.3 is completed. I'm still waiting on missing features in the 1.8.3 version.

**Comment by DSH105** [comment]
Missing features?

**Comment by Htgan** [comment]
It's in the previous issue #60 PetGoalMeleeAttack and I think one other one.

**Comment by sanjay900** [comment]
Mind you, 1.8.4 didn't actually change much NMS wise. For a lot of things, a simple find and replace was enough when i was testing.

**Comment by DSH105** [comment]
I haven't looked yet, but I would assume so. It shouldn't take long once I find the time to look into it.

**Comment by sanjay900** [comment]
I might have a look into it out of complete boredom. If i get something done ill make a pr.

**Comment by DSH105** [comment]
#526

**Comment by sanjay900** [comment]
That works too :)

**Comment by NotNorom** [comment]
Thank you a lot, Sir @DSH105 ! :)

**Comment by DSH105** [comment]
:D
