### ISSUE TITLE
EchoPet 2.8 - Rabbit, Guardian and Endermite not showing in /pet select GUI.

### ISSUE THREAD

**Issue by whoshenry** [DSH105/EchoPet#527]
As the title reads, the new mobs added are not shown in the menu to pick your pet.

**Comment by DSH105** [comment]
Those pets need to be manually added to an existing config as they will only appear in newly generated configs. 

You can: 
* temporarily save your existing config in a different location.
* start up your server and let a new config file form. 
* copy the sections corresponding to the guardian and rabbit pets over to your old config.
* replace the new config with your old config.

**Comment by whoshenry** [comment]
Oh yeah, I saw the config updated with the new mob settings, just not the menu entries. Thanks.
