### ISSUE TITLE
1.8.6 Support.

### ISSUE THREAD

**Issue by andrewkm** [DSH105/EchoPet#529]
Not sure where to look for updates, a possible thread, or dev builds for 1.8.6 support.
I remember there was a big ticket with information on 1.8 when that was happening. Is there a place to stay up to date for updates on the 1.8.6 release?

**Comment by DSH105** [comment]
There are no changes that need to be applied to EchoPet to be compatible with 1.8.6. As far as I'm aware, it's already compatible.

**Comment by andrewkm** [comment]
Oops, my bad totally missed something obvious, sorry lots on my head lately. This can be closed.

**Comment by DSH105** [comment]
No problem. Glad to see it's working :).
