### ISSUE TITLE
No permissions while having the permission

### ISSUE THREAD

**Issue by frank-2409** [DSH105/EchoPet#531]
I an issue with my echopet becouse when VIP's open the pet menu were they can set baby ride hat etc. it says: You do not have the permission to execute this command! But the menu opens correctly and everything works.
pls help me!

**Comment by ZyloV** [comment]
I am having the same exact problem, the only way to fix that is to give the group Echopet.pet.type.* but that will allow them to have all the animals. I need help as well.

**Comment by DSH105** [comment]
Can you show me your permissions file :)?

**Comment by ZyloV** [comment]
http://pastebin.com/uAxXLQC0

**Comment by ZyloV** [comment]
Still need help.

**Comment by DSH105** [comment]
You need to grant the attribute permissions (see [here](https://github.com/DSH105/EchoPet/wiki/Permissions#data-type-permissions)).

e.g. echopet.pet.type.cow.baby

**Comment by ZyloV** [comment]
What if i do echopet.pet.type.cow.* will that count?

**Comment by DSH105** [comment]
Yes, that will grant all data types relevant to the cow.

**Comment by bloggy** [comment]
I have the same problem and it does not work for me this way.
