### ISSUE TITLE
Disable pets in BedWarsRel game

### ISSUE THREAD

**Issue by Granik24** [DSH105/EchoPet#533]
Hey there, I have little question. It is possible to disalbe pets only ingame of this plugin? https://github.com/Yannici/bedwars-reloaded

Thanks.

**Comment by DSH105** [comment]
Yep, sure is :). Two options:
* If your game arenas are restricted to specific worlds, you can use the [worlds section of the config](https://github.com/DSH105/EchoPet/wiki/Config.yml#worlds-section) to prevent pets in those worlds.
* Alternatively, you can restrict pets within WorldGuard regions using the [regions section of the config](https://github.com/DSH105/EchoPet/wiki/Config.yml#region-blacklist-section).
