### ISSUE TITLE
Worldguard+EchoPet

### ISSUE THREAD

**Issue by MrCosgrove1** [DSH105/EchoPet#536]
If i had installed WorldGuard and Echopet together, EchoPet can´t create a mob !

This Message comes: An internal error occurred while attempting to perform this command.

If i delete WorldGuard all is perfectly working.

**Comment by DSH105** [comment]
and what internal error might that be?

**Comment by MrCosgrove1** [comment]
http://pastebin.com/4CndrUJy

**Comment by DSH105** [comment]
What versions of EchoPet and WorldGuard are you running?

**Comment by MrCosgrove1** [comment]
Craftbukkit: 1.7.9
Worldguard: WorldGuard 6.0 Beta 2 for 1.7.9
EchoPet: v2.3.3

**Comment by MrCosgrove1** [comment]
Please could you punish me?
I read your change-logs...
im a fucing idiot:
This release includes the support for all MC versions from 1.6.4 through to 1.7.8
This was supposed to be included in the previous versions, but was not. Sorry ;c

With 2.5.0 all is perfect working thx :3

**Comment by DSH105** [comment]
Awesome, glad to see its working :)!
