### ISSUE TITLE
Is there any way to make this work with Spigot 1.8

### ISSUE THREAD

**Issue by Derpninja1311** [DSH105/EchoPet#537]
So I got echopet and saw that it doesn't work with 1.8 spigot. That is odd, but is there any way to make it work with 1.8 spigot, or any other version. Also may you tell me why it doesn't work with 1.8 spigot so I might even be able to get my dev to make his own version that will work with my server?

**Comment by DSH105** [comment]
It does ;o.

Which version of EchoPet are you running?

**Comment by ItsHarry** [comment]
Hmm, in this commit 07f71f5 the 'v1_8_Spigot' compat was removed, but in ReflectionUtil, it still points to 'v1_8_Spigot'. Should it be changed to 'v1_7_R4'?
