### ISSUE TITLE
Paper Spigot 

### ISSUE THREAD

**Issue by mariolars** [DSH105/EchoPet#547]
Could you fix echo pet not loading on paper spigot?

**Comment by DSH105** [comment]
I'll need error reports to diagnose the issue :).

**Comment by mariolars** [comment]
Ok, You fixed it with newer version. I'm really greatful for this.

**Comment by DSH105** [comment]
Awesome, so this ticket is resolved now? ;D

**Comment by mariolars** [comment]
yep
