### ISSUE TITLE
1.8 pets?

### ISSUE THREAD

**Issue by Hammytheturtle** [DSH105/EchoPet#550]
So I got the plugin on my spigot 1.8 server, It works fine, I have all the donator ranks working with certain pets, but the Rabbit, Guardian, and Endermite seem to not have a given name on here "https://github.com/DSH105/EchoPet/wiki/Permissions" and I tried just vanilla names for them like "endermite" ect... in group manager but they still do not work? You are able to ride them and wear them but not turn them into babies or killer bunny ect... although it gives you the option, I have the wrong perms, so could someone tell me what there perm would be to fit in here "https://github.com/DSH105/EchoPet/wiki/Permissions", Please ? I need to know there pet type permissions.

**Comment by i9hdkill** [comment]
Usually, if you try to enter an echopet command without permisions, you get a message that contains the needed permission node.
(Maybe you disabled that in your config)

**Comment by Hammytheturtle** [comment]
Oh, yes i did! Thankyou, I will try it now

**Comment by DSH105** [comment]
Permissions should be the same as they are listed in the config file.

**Comment by Hammytheturtle** [comment]
I tried that it didnt work, but i fixed it now
