### ISSUE TITLE
1.9 Support Please!

### ISSUE THREAD

**Issue by RarePika** [DSH105/EchoPet#606]
Spigot 1.9 recently lauched but the EchoPet plugin isn't compatible with 1.9. I really want to use it for my Spigot 1.9 server, but I can't. Please update it. Thank you.

**Comment by CaptainBern** [comment]
EchoPet is permanently discontinued.

**Comment by RarePika** [comment]
If I can't download a updated version, can you at least reference me to something that helps me update it myself?

**Comment by CaptainBern** [comment]
The source code in this repository :)

**Comment by RarePika** [comment]
OK. Honest, that didn't help to much, but OK. I'll try to figure it out myself. Thanks! 😃

**Comment by RarePika** [comment]
Ok, I give up. I can't learn GitHub. I can't update the thing. :-(

**Comment by FarisR99** [comment]
Honestly I have no idea how to set up my IntelliJ Maven projects with this SRC. It is very different to any other plugin SRC structure I've seen.

**Comment by net32** [comment]
https://github.com/Borlea/EchoPet
