### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by FarisR99** [DSH105/EchoPet#607]
I'm not exactly sure where to put this, so I decided to make an issue to make sure it's seen.

I was wondering how exactly do I modify the SRC and compile EchoPet. I attempted to fork this project and download it, creating a Maven project from it. However I encountered MANY errors such as EchoPets-API not existing, EchoPets-Parent not existing and I have no idea how to use this project in general. It is VERY different to any plugin I've ever seen on GitHub.

**Comment by CaptainBern** [comment]
EchoPet uses a Module system in order to be compatible with as many Minecraft versions as possible. Take a look [here](https://bukkit.org/threads/support-multiple-minecraft-versions-with-abstraction-maven.115810/) to see how this works.

**Comment by FarisR99** [comment]
Never mind, I'll just switch to MyPets instead. Thanks anyway =)
